pipeline {
	agent any

    tools {
		maven 'maven'
        jdk 'jdk17'
    }

    stages {
		stage('Build') {
			steps {
				bat 'mvn clean compile'
            }
        }
        stage('Test') {
			steps {
				bat 'mvn test'
            }
        }
        stage('Package') {
			steps {
				bat 'mvn package'
            }
        }
    }
}
