pipeline {
	agent any

    tools {
		jdk 'jdk17'
    }

    environment {
        MVN_HOME = tool name: 'maven', type: 'hudson.tasks.Maven$MavenInstallation'
        MVN = "%MVN_HOME%\\bin\\mvn.cmd"
    }

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Build') {
			steps {
				bat "\"%MVN%\" -v"
                bat "\"%MVN%\" -B -f backend/pom.xml clean compile"
            }
        }

        stage('Test') {
			steps {
				bat "\"%MVN%\" -B -f backend/pom.xml test"
            }
            post {
				always {
					junit 'backend/**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
			steps {
				bat "\"%MVN%\" -B -f backend/pom.xml package"
            }
        }
    }

    post {
		success {
			archiveArtifacts artifacts: 'backend/**/target/*.jar', fingerprint: true
        }
    }
}
